# Generated by Django 2.1.5 on 2019-01-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='address',
            field=models.CharField(default='www.google.com', max_length=255),
        ),
    ]
