# Generated by Django 2.1.5 on 2019-01-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_work_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='address_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='work',
            name='address_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='work',
            name='address_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='work',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='work',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='work',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
    ]
