# Generated by Django 2.1.5 on 2019-01-13 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20190112_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='photo_1',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='photo_2',
            new_name='image_2',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='photo_3',
            new_name='image_3',
        ),
    ]
