# Generated by Django 2.1.5 on 2019-01-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20190112_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='summary',
            new_name='title',
        ),
        migrations.AddField(
            model_name='work',
            name='highlights_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='work',
            name='highlights_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='work',
            name='highlights_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='work',
            name='highlights_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='work',
            name='highlights_6',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='work',
            name='highlights_7',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
