# Generated by Django 2.1.5 on 2019-01-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20190112_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='highlights_4',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
