# Generated by Django 2.1.5 on 2019-01-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='address',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
