# Generated by Django 2.1.5 on 2019-01-11 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190110_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='address',
        ),
    ]
