# Generated by Django 3.2 on 2021-05-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='body2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='body3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='body4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='image1',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image3',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image4',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
