# Generated by Django 3.2 on 2021-05-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210503_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.TextField(),
        ),
    ]
